// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0_CA0HrRxTgHhJPxN9z3OzDU1NYweF1w',
    appId: '1:766878052661:web:b5f3568808efddf5dedc7c',
    messagingSenderId: '766878052661',
    projectId: 'cbsd-project-29f3c',
    authDomain: 'cbsd-project-29f3c.firebaseapp.com',
    storageBucket: 'cbsd-project-29f3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy9lhQn83A2gUkI52tzPQosZhV9qWXer0',
    appId: '1:766878052661:android:2d18fd5e82c71ad9dedc7c',
    messagingSenderId: '766878052661',
    projectId: 'cbsd-project-29f3c',
    storageBucket: 'cbsd-project-29f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpFuId_cES6EMSdWig14PJPPb1dwu3ag',
    appId: '1:766878052661:ios:14c13edff59ec3c4dedc7c',
    messagingSenderId: '766878052661',
    projectId: 'cbsd-project-29f3c',
    storageBucket: 'cbsd-project-29f3c.firebasestorage.app',
    iosBundleId: 'com.example.caloriestarcker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSpFuId_cES6EMSdWig14PJPPb1dwu3ag',
    appId: '1:766878052661:ios:14c13edff59ec3c4dedc7c',
    messagingSenderId: '766878052661',
    projectId: 'cbsd-project-29f3c',
    storageBucket: 'cbsd-project-29f3c.firebasestorage.app',
    iosBundleId: 'com.example.caloriestarcker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0_CA0HrRxTgHhJPxN9z3OzDU1NYweF1w',
    appId: '1:766878052661:web:93da45bc3b4ad07fdedc7c',
    messagingSenderId: '766878052661',
    projectId: 'cbsd-project-29f3c',
    authDomain: 'cbsd-project-29f3c.firebaseapp.com',
    storageBucket: 'cbsd-project-29f3c.firebasestorage.app',
  );
}
